"""
Response parser — the single entry point for running a full AI analysis.

Orchestrates:
  1. Cache lookup
  2. RAG retrieval
  3. Prompt construction
  4. Ollama inference
  5. JSON extraction & validation
  6. Cache write
"""
from __future__ import annotations

import logging
import time
from typing import Optional

from app.ai import cache as _cache
from app.ai.ollama_client import generate, is_ollama_running
from app.ai.prompt_builder import build_prompt, build_rag_query
from app.ai.rag import retriever
from app.ai.validator import extract_json

logger = logging.getLogger(__name__)


def analyze_product(product, profile) -> dict:
    """
    Run the full RAG + Phi-3 nutrition analysis pipeline.

    Parameters
    ----------
    product : app.models.product.Product ORM instance (or duck-typed object)
    profile : app.models.profile.UserProfile ORM instance, or None

    Returns
    -------
    Validated dict matching the standard AI analysis JSON schema.
    """
    # ── 1. Cache check ───────────────────────────────────────────────────────
    user_id  = getattr(profile, "user_id", 0) or 0
    p_hash   = _cache.profile_hash(profile)
    key      = _cache.make_key(getattr(product, "barcode", ""), user_id, p_hash)
    cached   = _cache.get(key)
    if cached:
        logger.info("Cache hit for barcode=%s user=%s", getattr(product, "barcode", "?"), user_id)
        return cached

    # ── 2. Ollama health check ────────────────────────────────────────────────
    if not is_ollama_running():
        logger.error("Ollama is not running — returning fallback result.")
        return _ollama_unavailable_result(product)

    # ── 3. RAG retrieval ─────────────────────────────────────────────────────
    t0 = time.perf_counter()
    query       = build_rag_query(product, profile)
    rag_context = retriever.retrieve(query, top_k=4)
    logger.debug("RAG retrieved %d docs in %.3fs", len(rag_context), time.perf_counter() - t0)

    # ── 4. Prompt construction ────────────────────────────────────────────────
    system_prompt, user_prompt = build_prompt(product, profile, rag_context)

    # ── 5. Inference ─────────────────────────────────────────────────────────
    t0 = time.perf_counter()
    try:
        raw_response = generate(
            prompt=user_prompt,
            system=system_prompt,
            temperature=0.15,    # very low — we want deterministic JSON
            max_tokens=1500,
            timeout=120,
        )
    except RuntimeError as exc:
        logger.error("Ollama inference failed: %s", exc)
        return _ollama_unavailable_result(product)

    logger.info("Phi-3 inference completed in %.2fs for barcode=%s",
                time.perf_counter() - t0, getattr(product, "barcode", "?"))

    # ── 6. Parse & validate ───────────────────────────────────────────────────
    result = extract_json(raw_response)

    # Attach metadata not generated by the model
    result["_source"]  = "phi3_rag"
    result["_barcode"] = getattr(product, "barcode", "")
    result["_cached"]  = False

    # ── 7. Cache write ────────────────────────────────────────────────────────
    _cache.set(key, result)

    return result


# ── Fallback ──────────────────────────────────────────────────────────────────

def _ollama_unavailable_result(product) -> dict:
    """Return a safe default result when Ollama is not available."""
    return {
        "overall_score": 0,
        "health_rating": "Fair",
        "summary": (
            "AI analysis is temporarily unavailable because Ollama is not running. "
            "Please start Ollama with 'ollama serve' and try again."
        ),
        "pros": [],
        "cons": [],
        "warnings": ["AI nutrition analysis requires Ollama to be running locally."],
        "recommended_for": [],
        "avoid_if": [],
        "better_alternatives": [],
        "daily_limit": "N/A — AI unavailable",
        "personalized_advice": "Start Ollama (`ollama serve`) to enable AI analysis.",
        "confidence": 0.0,
        "_source": "fallback",
        "_barcode": getattr(product, "barcode", ""),
        "_cached": False,
    }
